
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        make all-via-docker
    - name: Install ckb-debugger
      run: |
        cd ..
        git clone https://github.com/nervosnetwork/ckb-standalone-debugger
        cd ckb-standalone-debugger/bins
        cargo install --path .
    - name: Run cases
      run: |
        cd tests/official && make ci
        cd ../test_cases && make ci
        cd ../ckb-c-stdlib-tests && make all-via-docker && make ci
